name: Build and Deploy HouseTracker

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠 Install GCC 13 and dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 zip unzip pkg-config curl git software-properties-common ninja-build
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: 🧱 Install latest CMake (from Kitware)
        run: |
          sudo apt-get purge -y cmake || true
          sudo apt-get install -y wget gpg lsb-release
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc \
            | gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
            | sudo tee /etc/apt/sources.list.d/kitware.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: 📦 Bootstrap vcpkg and install packages
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install
          echo "VCPKG_TOOLCHAIN_FILE=$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

      - name: 🔨 Build HouseTracker
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_TOOLCHAIN_FILE }} \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
            -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_SKIP_RPATH=ON
          cmake --build . --config Release
          cd ..

      - name: 🚚 Upload to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/HouseTracker"
          target: "/home/${{ secrets.VPS_USERNAME }}/house-tracker/build/HouseTracker.new"

      - name: 🚀 Restart Binary on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/house-tracker/build
            if [ -f HouseTracker.new ]; then
              sudo systemctl stop house-tracker
              mv ./HouseTracker.new/build/HouseTracker HouseTracker
              chmod +x HouseTracker
              sudo systemctl start house-tracker
            fi
